<script setup lang="ts">
import { ref } from 'vue'
import { Sparkles, Check, X, AlertTriangle, RotateCcw, ShieldCheck, UserCheck } from 'lucide-vue-next'
import type { ErumiRoadmapDiffProposalDto } from '../types'

const props = defineProps<{
  show: boolean
  proposal: ErumiRoadmapDiffProposalDto | null
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'approve'): void
}>()
</script>

<template>
  <div v-if="show && proposal" class="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
    <div class="glass-card bg-slate-900 border border-purple-500/50 rounded-2xl max-w-2xl w-full p-6 space-y-5 shadow-2xl animate-in fade-in zoom-in duration-200">
      <div class="flex items-center justify-between border-b border-slate-800 pb-3">
        <div class="flex items-center gap-2 text-purple-400 font-bold text-base">
          <Sparkles class="w-5 h-5" />
          <span>✨ AI Roadmap Change Proposal (Diff Preview)</span>
        </div>
        <button @click="emit('close')" class="text-slate-400 hover:text-white transition">
          <X class="w-5 h-5" />
        </button>
      </div>

      <div class="space-y-4 text-xs">
        <div class="bg-purple-500/10 border border-purple-500/30 p-3 rounded-xl flex items-center justify-between">
          <div>
            <div class="text-white font-bold text-sm">{{ proposal.phaseName }}</div>
            <div class="text-purple-300 text-[11px]">{{ proposal.summary }}</div>
          </div>
          <span class="bg-purple-500/20 text-purple-300 px-2.5 py-1 rounded-full border border-purple-500/40 font-mono text-[10px]">
            Before Approval
          </span>
        </div>

        <!-- Proposed Tasks Grid -->
        <div class="space-y-2">
          <div class="text-emerald-400 font-bold flex items-center gap-1.5">
            <Check class="w-4 h-4" />
            <span>+ {{ proposal.proposedTasks.length }} Task Mới Sẽ Tạo (Gắn Nhãn 🤖 Generated by Erumi AI):</span>
          </div>

          <div class="space-y-2 max-h-48 overflow-y-auto pr-1">
            <div
              v-for="task in proposal.proposedTasks"
              :key="task.title"
              class="bg-slate-950 p-3 rounded-xl border border-slate-800 space-y-1"
            >
              <div class="flex items-center justify-between text-white font-semibold">
                <span class="text-purple-300">{{ task.title }}</span>
                <span class="bg-slate-800 text-slate-300 px-2 py-0.5 rounded text-[10px]">{{ task.priority }} • {{ task.estimatedHours }}h</span>
              </div>
              <p class="text-slate-400 text-[11px]">{{ task.description }}</p>
              <div class="text-[10px] text-slate-500 flex items-center gap-1 pt-1">
                <UserCheck class="w-3 h-3 text-purple-400" />
                <span>Gán khuyến nghị: <strong class="text-slate-300">{{ task.recommendedAssigneeName || 'Auto' }}</strong> ({{ task.recommendedRole }})</span>
              </div>
            </div>
          </div>
        </div>

        <!-- Workload Impact Analysis -->
        <div class="space-y-2">
          <div class="text-blue-400 font-bold">📊 Capacity & Workload Impact (Kiểm Tra Khả Năng Chịu Tải Team):</div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
            <div
              v-for="impact in proposal.workloadImpacts"
              :key="impact.memberUserId"
              class="bg-slate-950 p-2.5 rounded-lg border text-[11px] space-y-1"
              :class="impact.isOverloaded ? 'border-rose-500/40 bg-rose-500/5' : 'border-emerald-500/30 bg-emerald-500/5'"
            >
              <div class="flex items-center justify-between font-semibold">
                <span class="text-white">{{ impact.memberName }}</span>
                <span :class="impact.isOverloaded ? 'text-rose-400 font-bold' : 'text-emerald-400'">
                  {{ impact.warningMessage }}
                </span>
              </div>
              <div class="text-slate-400">
                Vai trò: {{ impact.currentRole }} • Tải mới thêm: +{{ impact.proposedAdditionalHours }}h
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="flex items-center justify-between pt-3 border-t border-slate-800 text-xs">
        <div class="text-slate-400 flex items-center gap-1">
          <RotateCcw class="w-3.5 h-3.5 text-purple-400" />
          <span>Hỗ trợ 1-Click Rollback / Undo trong 24h</span>
        </div>

        <div class="flex items-center space-x-3">
          <button
            @click="emit('close')"
            class="bg-slate-800 hover:bg-slate-700 text-slate-300 px-4 py-2 rounded-lg transition"
          >
            Hủy Bỏ
          </button>
          <button
            @click="emit('approve')"
            class="bg-gradient-to-r from-purple-600 to-indigo-600 hover:opacity-90 text-white font-bold px-5 py-2 rounded-lg transition shadow-md shadow-purple-500/30 flex items-center gap-1.5"
          >
            <Check class="w-4 h-4" />
            <span>Phê Duyệt & Đẩy Vào Roadmap</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
