import type { DashboardResponse } from './types'

export const fallbackDashboard: DashboardResponse = {
  generatedAt: '2026-05-01T16:20:00Z',
  stats: {
    activeProjects: 3,
    totalTasks: 18,
    overdueTasks: 2,
    teamMembers: 7,
    completedTasks: 7,
    completionRate: 39,
    tasksAtRisk: 5,
  },
  summary:
    'Qaly đang điều phối nhiều luồng triển khai cho MVP, xác thực và hệ thống thiết kế. Không gian làm việc được tối ưu cho lập kế hoạch nhanh, hiển thị rủi ro rõ ràng và hỗ trợ quyết định bằng AI.',
  riskDigest:
    'Các điểm áp lực chính là công việc triển khai quá hạn, tải công việc chưa đều trong đội nòng cốt và một nhóm nhỏ việc ưu tiên cao vẫn chờ người phụ trách rõ ràng.',
  projects: [
    {
      id: '3f9f7728-40d6-4fd3-bfef-90f7fdad7001',
      name: 'Qaly MVP',
      description:
        'Không gian quản lý công việc nội bộ cho triển khai chu kỳ làm việc, lập kế hoạch đội ngũ và hỗ trợ quyết định bằng AI.',
      status: 'Active',
      ownerId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3001',
      ownerName: 'Quản trị viên',
      memberCount: 3,
      taskCount: 8,
      completedTaskCount: 3,
      overdueTaskCount: 1,
      progressPercentage: 38,
      members: [
        {
          userId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3001',
          fullName: 'Quản trị viên',
          role: 'Owner',
          email: 'admin@qaly.dev',
        },
        {
          userId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3002',
          fullName: 'Nguyễn Văn A',
          role: 'Member',
          email: 'nguyenvana@qaly.dev',
        },
        {
          userId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3003',
          fullName: 'Trần Thị B',
          role: 'Member',
          email: 'tranthib@qaly.dev',
        },
      ],
      createdAt: '2026-04-20T09:00:00Z',
      endDate: '2026-07-31T17:00:00Z',
      tasks: [
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2001',
          title: 'Thiết kế khung làm việc',
          status: 'Done',
          priority: 'High',
          dueDate: '2026-04-24T17:00:00Z',
          assigneeName: 'Quản trị viên',
          reporterName: 'Quản trị viên',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 3,
          attachmentCount: 1,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2002',
          title: 'Triển khai API chỉ số bảng điều khiển',
          status: 'InProgress',
          priority: 'High',
          dueDate: '2026-05-03T17:00:00Z',
          assigneeName: 'Nguyễn Văn A',
          reporterName: 'Quản trị viên',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 5,
          attachmentCount: 0,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2003',
          title: 'Tạo trạng thái tương tác Kanban',
          status: 'Todo',
          priority: 'Medium',
          dueDate: '2026-05-07T17:00:00Z',
          assigneeName: 'Trần Thị B',
          reporterName: 'Quản trị viên',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 2,
          attachmentCount: 0,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2004',
          title: 'Tích hợp bề mặt gợi ý AI',
          status: 'Todo',
          priority: 'High',
          dueDate: '2026-05-05T17:00:00Z',
          assigneeName: null,
          reporterName: 'Quản trị viên',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 1,
          attachmentCount: 0,
        },
      ],
    },
    {
      id: '3f9f7728-40d6-4fd3-bfef-90f7fdad7002',
      name: 'Gia cố định danh',
      description: 'Phân quyền theo vai trò, an toàn phiên đăng nhập và trải nghiệm đăng nhập/đăng ký.',
      status: 'InProgress',
      ownerId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3002',
      ownerName: 'Nguyễn Văn A',
      memberCount: 2,
      taskCount: 5,
      completedTaskCount: 2,
      overdueTaskCount: 1,
      progressPercentage: 40,
      members: [
        {
          userId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3002',
          fullName: 'Nguyễn Văn A',
          role: 'Owner',
          email: 'nguyenvana@qaly.dev',
        },
        {
          userId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3003',
          fullName: 'Trần Thị B',
          role: 'Member',
          email: 'tranthib@qaly.dev',
        },
      ],
      createdAt: '2026-04-18T09:00:00Z',
      endDate: '2026-06-14T17:00:00Z',
      tasks: [
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2010',
          title: 'Xác thực trang đăng ký',
          status: 'Done',
          priority: 'Medium',
          dueDate: '2026-04-26T17:00:00Z',
          assigneeName: 'Nguyễn Văn A',
          reporterName: 'Nguyễn Văn A',
          projectName: 'Gia cố định danh',
          isPrivate: false,
          commentCount: 1,
          attachmentCount: 0,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2011',
          title: 'Triển khai middleware phân quyền',
          status: 'InProgress',
          priority: 'High',
          dueDate: '2026-05-02T17:00:00Z',
          assigneeName: 'Trần Thị B',
          reporterName: 'Nguyễn Văn A',
          projectName: 'Gia cố định danh',
          isPrivate: false,
          commentCount: 4,
          attachmentCount: 0,
        },
      ],
    },
    {
      id: '3f9f7728-40d6-4fd3-bfef-90f7fdad7003',
      name: 'Ngôn ngữ thiết kế',
      description:
        'Hoàn thiện hệ thống hình ảnh, kiểu chữ và các mẫu giao diện tái sử dụng cho quy trình quản trị.',
      status: 'Planned',
      ownerId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3003',
      ownerName: 'Trần Thị B',
      memberCount: 2,
      taskCount: 5,
      completedTaskCount: 2,
      overdueTaskCount: 0,
      progressPercentage: 40,
      members: [
        {
          userId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3003',
          fullName: 'Trần Thị B',
          role: 'Owner',
          email: 'tranthib@qaly.dev',
        },
        {
          userId: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3001',
          fullName: 'Quản trị viên',
          role: 'Member',
          email: 'admin@qaly.dev',
        },
      ],
      createdAt: '2026-04-15T09:00:00Z',
      endDate: '2026-06-28T17:00:00Z',
      tasks: [
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2020',
          title: 'Xây dựng hệ màu',
          status: 'Done',
          priority: 'Medium',
          dueDate: '2026-04-23T17:00:00Z',
          assigneeName: 'Trần Thị B',
          reporterName: 'Quản trị viên',
          projectName: 'Ngôn ngữ thiết kế',
          isPrivate: false,
          commentCount: 2,
          attachmentCount: 1,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2021',
          title: 'Rà soát khung tương thích đa màn hình',
          status: 'Todo',
          priority: 'Medium',
          dueDate: '2026-05-09T17:00:00Z',
          assigneeName: 'Quản trị viên',
          reporterName: 'Trần Thị B',
          projectName: 'Ngôn ngữ thiết kế',
          isPrivate: false,
          commentCount: 0,
          attachmentCount: 0,
        },
      ],
    },
  ],
  team: [
    {
      id: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3001',
      fullName: 'Quản trị viên',
      role: 'Admin',
      email: 'admin@qaly.dev',
      isActive: true,
      assignedTaskCount: 5,
      completedTaskCount: 2,
      inProgressTaskCount: 1,
      overdueTaskCount: 0,
      capacityPercent: 68,
      focusArea: 'Điều phối dự án',
    },
    {
      id: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3002',
      fullName: 'Nguyễn Văn A',
      role: 'Member',
      email: 'nguyenvana@qaly.dev',
      isActive: true,
      assignedTaskCount: 4,
      completedTaskCount: 1,
      inProgressTaskCount: 2,
      overdueTaskCount: 1,
      capacityPercent: 83,
      focusArea: 'Luồng triển khai',
    },
    {
      id: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3003',
      fullName: 'Trần Thị B',
      role: 'Member',
      email: 'tranthib@qaly.dev',
      isActive: true,
      assignedTaskCount: 3,
      completedTaskCount: 1,
      inProgressTaskCount: 1,
      overdueTaskCount: 1,
      capacityPercent: 72,
      focusArea: 'Hệ thống thiết kế',
    },
  ],
  notifications: [
    {
      id: 'note-1',
      title: 'Rủi ro tăng đột biến',
      message: 'Gia cố định danh có một công việc ưu tiên cao đến hạn trong 24 giờ.',
      tone: 'critical',
      createdAt: '2026-05-01T16:00:00Z',
    },
    {
      id: 'note-2',
      title: 'Tải công việc chưa cân bằng',
      message: 'Nguyễn Văn A đang nhận số công việc đang mở cao nhất trong chu kỳ làm việc này.',
      tone: 'warning',
      createdAt: '2026-05-01T15:20:00Z',
    },
    {
      id: 'note-3',
      title: 'Trợ lý AI đã sẵn sàng',
      message:
        'Tóm tắt thông minh, quét rủi ro và gợi ý hội thoại đã sẵn sàng cho dự án đang chọn.',
      tone: 'info',
      createdAt: '2026-05-01T14:45:00Z',
    },
  ],
}
