import type { DashboardResponse } from './types'

export const fallbackDashboard: DashboardResponse = {
  generatedAt: '2026-05-01T16:20:00Z',
  stats: {
    activeProjects: 3,
    totalTasks: 18,
    overdueTasks: 2,
    teamMembers: 7,
    completedTasks: 7,
    completionRate: 39,
    tasksAtRisk: 5,
  },
  summary:
    'Qaly is coordinating multiple delivery streams across the MVP, authentication, and design system tracks. The workspace is optimized for fast planning, visible risk, and AI-assisted decision support.',
  riskDigest:
    'The main pressure points are overdue implementation tasks, uneven workload across the core team, and a small cluster of high-priority items still waiting for a clear owner.',
  projects: [
    {
      id: '3f9f7728-40d6-4fd3-bfef-90f7fdad7001',
      name: 'Qaly MVP',
      description:
        'Internal project management workspace for sprint execution, team planning, and AI-assisted delivery.',
      status: 'Active',
      ownerName: 'Admin User',
      memberCount: 3,
      taskCount: 8,
      completedTaskCount: 3,
      overdueTaskCount: 1,
      progressPercentage: 38,
      memberNames: ['Admin User', 'Nguyen Van A', 'Tran Thi B'],
      createdAt: '2026-04-20T09:00:00Z',
      endDate: '2026-07-31T17:00:00Z',
      tasks: [
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2001',
          title: 'Design workspace shell',
          status: 'Done',
          priority: 'High',
          dueDate: '2026-04-24T17:00:00Z',
          assigneeName: 'Admin User',
          reporterName: 'Admin User',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 3,
          attachmentCount: 1,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2002',
          title: 'Implement dashboard metrics API',
          status: 'InProgress',
          priority: 'High',
          dueDate: '2026-05-03T17:00:00Z',
          assigneeName: 'Nguyen Van A',
          reporterName: 'Admin User',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 5,
          attachmentCount: 0,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2003',
          title: 'Create Kanban interaction states',
          status: 'Todo',
          priority: 'Medium',
          dueDate: '2026-05-07T17:00:00Z',
          assigneeName: 'Tran Thi B',
          reporterName: 'Admin User',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 2,
          attachmentCount: 0,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2004',
          title: 'Integrate AI insight surfaces',
          status: 'Todo',
          priority: 'High',
          dueDate: '2026-05-05T17:00:00Z',
          assigneeName: null,
          reporterName: 'Admin User',
          projectName: 'Qaly MVP',
          isPrivate: false,
          commentCount: 1,
          attachmentCount: 0,
        },
      ],
    },
    {
      id: '3f9f7728-40d6-4fd3-bfef-90f7fdad7002',
      name: 'Identity Hardening',
      description: 'Role-based access, session safety, and login/register experience.',
      status: 'InProgress',
      ownerName: 'Nguyen Van A',
      memberCount: 2,
      taskCount: 5,
      completedTaskCount: 2,
      overdueTaskCount: 1,
      progressPercentage: 40,
      memberNames: ['Nguyen Van A', 'Tran Thi B'],
      createdAt: '2026-04-18T09:00:00Z',
      endDate: '2026-06-14T17:00:00Z',
      tasks: [
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2010',
          title: 'Register page validation',
          status: 'Done',
          priority: 'Medium',
          dueDate: '2026-04-26T17:00:00Z',
          assigneeName: 'Nguyen Van A',
          reporterName: 'Nguyen Van A',
          projectName: 'Identity Hardening',
          isPrivate: false,
          commentCount: 1,
          attachmentCount: 0,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2011',
          title: 'Permission middleware rollout',
          status: 'InProgress',
          priority: 'High',
          dueDate: '2026-05-02T17:00:00Z',
          assigneeName: 'Tran Thi B',
          reporterName: 'Nguyen Van A',
          projectName: 'Identity Hardening',
          isPrivate: false,
          commentCount: 4,
          attachmentCount: 0,
        },
      ],
    },
    {
      id: '3f9f7728-40d6-4fd3-bfef-90f7fdad7003',
      name: 'Design Language',
      description:
        'Landing the visual system, typography, and reusable UI patterns for admin workflows.',
      status: 'Planned',
      ownerName: 'Tran Thi B',
      memberCount: 2,
      taskCount: 5,
      completedTaskCount: 2,
      overdueTaskCount: 0,
      progressPercentage: 40,
      memberNames: ['Tran Thi B', 'Admin User'],
      createdAt: '2026-04-15T09:00:00Z',
      endDate: '2026-06-28T17:00:00Z',
      tasks: [
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2020',
          title: 'Craft color system',
          status: 'Done',
          priority: 'Medium',
          dueDate: '2026-04-23T17:00:00Z',
          assigneeName: 'Tran Thi B',
          reporterName: 'Admin User',
          projectName: 'Design Language',
          isPrivate: false,
          commentCount: 2,
          attachmentCount: 1,
        },
        {
          id: '0ca40d7d-93aa-42d0-b9f6-2d2d9a5f2021',
          title: 'Responsive shell audit',
          status: 'Todo',
          priority: 'Medium',
          dueDate: '2026-05-09T17:00:00Z',
          assigneeName: 'Admin User',
          reporterName: 'Tran Thi B',
          projectName: 'Design Language',
          isPrivate: false,
          commentCount: 0,
          attachmentCount: 0,
        },
      ],
    },
  ],
  team: [
    {
      id: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3001',
      fullName: 'Admin User',
      role: 'Admin',
      email: 'admin@qaly.dev',
      isActive: true,
      assignedTaskCount: 5,
      completedTaskCount: 2,
      inProgressTaskCount: 1,
      overdueTaskCount: 0,
      capacityPercent: 68,
      focusArea: 'Project coordination',
    },
    {
      id: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3002',
      fullName: 'Nguyen Van A',
      role: 'Member',
      email: 'nguyenvana@qaly.dev',
      isActive: true,
      assignedTaskCount: 4,
      completedTaskCount: 1,
      inProgressTaskCount: 2,
      overdueTaskCount: 1,
      capacityPercent: 83,
      focusArea: 'Execution stream',
    },
    {
      id: '9f8e7d6c-1a2b-4f3c-9c8b-7a6d5e4f3003',
      fullName: 'Tran Thi B',
      role: 'Member',
      email: 'tranthib@qaly.dev',
      isActive: true,
      assignedTaskCount: 3,
      completedTaskCount: 1,
      inProgressTaskCount: 1,
      overdueTaskCount: 1,
      capacityPercent: 72,
      focusArea: 'Design systems',
    },
  ],
  notifications: [
    {
      id: 'note-1',
      title: 'Risk spike detected',
      message: 'Identity Hardening has one high-priority task due within 24 hours.',
      tone: 'critical',
      createdAt: '2026-05-01T16:00:00Z',
    },
    {
      id: 'note-2',
      title: 'Workload imbalance',
      message: 'Nguyen Van A is carrying the highest active task count this sprint.',
      tone: 'warning',
      createdAt: '2026-05-01T15:20:00Z',
    },
    {
      id: 'note-3',
      title: 'AI copilot ready',
      message:
        'Smart summary, risk scan, and assistant prompts are available for the active project.',
      tone: 'info',
      createdAt: '2026-05-01T14:45:00Z',
    },
  ],
}
