using Microsoft.EntityFrameworkCore;
using Qaly.Application.Common.Models;
using Qaly.Application.DTOs.Ai;
using Qaly.Domain.Entities;
using Qaly.Domain.Interfaces;

namespace Qaly.Application.Services;

public class ErumiRoadmapAiService : IErumiRoadmapAiService
{
    private readonly IRepository<Project> _projectRepo;
    private readonly IRepository<Sprint> _sprintRepo;
    private readonly IRepository<TaskItem> _taskRepo;
    private readonly IRepository<ProjectMember> _memberRepo;
    private readonly IRepository<SystemModulePermission> _systemPermRepo;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ICurrentUserService _currentUserService;
    private readonly IAuditLogService _auditLogService;

    // Cache tạm cho snapshots để phục vụ Rollback
    private static readonly Dictionary<Guid, (Guid SprintId, List<Guid> TaskIds, DateTimeOffset CreatedAt)> _snapshots = new();

    public ErumiRoadmapAiService(
        IRepository<Project> projectRepo,
        IRepository<Sprint> sprintRepo,
        IRepository<TaskItem> taskRepo,
        IRepository<ProjectMember> memberRepo,
        IRepository<SystemModulePermission> systemPermRepo,
        IUnitOfWork unitOfWork,
        ICurrentUserService currentUserService,
        IAuditLogService auditLogService)
    {
        _projectRepo = projectRepo;
        _sprintRepo = sprintRepo;
        _taskRepo = taskRepo;
        _memberRepo = memberRepo;
        _systemPermRepo = systemPermRepo;
        _unitOfWork = unitOfWork;
        _currentUserService = currentUserService;
        _auditLogService = auditLogService;
    }

    public async Task<Result<ErumiChatResponseDto>> ChatAndProposeRoadmapAsync(ErumiChatRequestDto dto, CancellationToken ct = default)
    {
        var currentUserId = _currentUserService.UserId;
        if (currentUserId == null) return Result.Forbidden<ErumiChatResponseDto>();

        // Check System Permission & AI Tier
        var userRole = _currentUserService.Role ?? "User";
        var systemPerm = await _systemPermRepo.GetQueryable()
            .FirstOrDefaultAsync(p => p.SystemRole == userRole && p.ModuleKey == "AiHub", ct);

        if (systemPerm != null && !systemPerm.IsAllowed)
        {
            return Result.Failure<ErumiChatResponseDto>("Tài khoản của bạn đã bị System Admin giới hạn tính năng AI.", 403);
        }

        var project = await _projectRepo.GetByIdAsync(dto.ProjectId, ct);
        if (project == null) return Result.NotFound<ErumiChatResponseDto>();

        // Lấy danh sách thành viên dự án & vai trò để phân bổ workload
        var members = await _memberRepo.GetQueryable()
            .Include(m => m.User)
            .Where(m => m.ProjectId == dto.ProjectId)
            .ToListAsync(ct);

        var snapshotId = Guid.NewGuid();
        var phaseName = "Phase 4: Security & Performance Hardening";
        var startDate = DateTimeOffset.UtcNow.AddDays(1);
        var endDate = startDate.AddDays(14);

        // Sinh danh sách task với tag 🤖 Generated by Erumi AI
        var proposedTasks = new List<ErumiTaskProposalDto>
        {
            new ErumiTaskProposalDto(
                "🤖 Generated by Erumi AI: Hardening Authentication & Audit Logging",
                "Triển khai Rate Limiting, Middleware Audit Log & Security Headers cho API.",
                "High",
                12,
                "Dev Backend",
                members.FirstOrDefault(m => m.Role.Contains("Backend") || m.Role.Contains("Dev"))?.UserId,
                members.FirstOrDefault(m => m.Role.Contains("Backend") || m.Role.Contains("Dev"))?.User?.FullName ?? "Dev Backend"
            ),
            new ErumiTaskProposalDto(
                "🤖 Generated by Erumi AI: Playwright Automated Security E2E Test Suite",
                "Viết bộ kịch bản test tự động kiểm tra rò rỉ dữ liệu Private Task & Permissions Matrix.",
                "High",
                16,
                "QA Lead",
                members.FirstOrDefault(m => m.Role.Contains("QA") || m.Role.Contains("Tester"))?.UserId,
                members.FirstOrDefault(m => m.Role.Contains("QA") || m.Role.Contains("Tester"))?.User?.FullName ?? "QA Lead"
            ),
            new ErumiTaskProposalDto(
                "🤖 Generated by Erumi AI: SignalR Real-Time Invalidation Cache",
                "Tối ưu Pinia store refetch bằng SignalR Permission Hub.",
                "Medium",
                8,
                "Dev Frontend",
                members.FirstOrDefault(m => m.Role.Contains("Frontend"))?.UserId,
                members.FirstOrDefault(m => m.Role.Contains("Frontend"))?.User?.FullName ?? "Dev Frontend"
            )
        };

        var workloadImpacts = members.Select(m => new ErumiWorkloadImpactDto(
            m.UserId,
            m.User?.FullName ?? "Member",
            m.Role,
            24,
            proposedTasks.Where(t => t.RecommendedAssigneeId == m.UserId).Sum(t => t.EstimatedHours),
            proposedTasks.Where(t => t.RecommendedAssigneeId == m.UserId).Sum(t => t.EstimatedHours) + 24 > 40,
            proposedTasks.Where(t => t.RecommendedAssigneeId == m.UserId).Sum(t => t.EstimatedHours) + 24 > 40
                ? "⚠️ Nguy cơ quá tải (>40h/tuần)"
                : "✔️ Khả năng chịu tải an toàn"
        )).ToList();

        var proposal = new ErumiRoadmapDiffProposalDto(
            snapshotId,
            dto.ProjectId,
            phaseName,
            startDate,
            endDate,
            proposedTasks,
            workloadImpacts,
            "Đề xuất 3 Task mới nhằm gia cố bảo mật và hiệu năng dự án Qaly."
        );

        var replyMessage = $"Chào bạn! Dựa trên bối cảnh hiện tại của {project.Name}, Erumi AI đề xuất chèn Phase mới vào Lộ trình.";

        return Result.Success(new ErumiChatResponseDto(replyMessage, true, proposal));
    }

    public async Task<Result> ApproveRoadmapProposalAsync(ApproveErumiRoadmapProposalDto dto, CancellationToken ct = default)
    {
        var currentUserId = _currentUserService.UserId;
        if (currentUserId == null) return Result.Forbidden();

        var project = await _projectRepo.GetByIdAsync(dto.ProjectId, ct);
        if (project == null) return Result.NotFound();

        // 1. Tạo Sprint mới
        var sprint = new Sprint
        {
            ProjectId = dto.ProjectId,
            Name = "Phase 4: Security & Performance Hardening (Erumi AI)",
            Goal = "Gia cố bảo mật API, phân quyền đa tầng & test tự động",
            StartDate = DateTimeOffset.UtcNow,
            EndDate = DateTimeOffset.UtcNow.AddDays(14),
            Status = "Planning"
        };
        await _sprintRepo.AddAsync(sprint, ct);
        await _unitOfWork.SaveChangesAsync(ct);

        // 2. Tạo các Tasks và đẩy vào Database/Kanban
        var createdTaskIds = new List<Guid>();
        foreach (var taskDto in dto.ApprovedTasks)
        {
            var task = new TaskItem
            {
                ProjectId = dto.ProjectId,
                SprintId = sprint.Id,
                Title = taskDto.Title.StartsWith("🤖") ? taskDto.Title : $"🤖 Generated by Erumi AI: {taskDto.Title}",
                Description = taskDto.Description,
                Priority = taskDto.Priority,
                EstimatedHours = taskDto.EstimatedHours,
                AssigneeId = taskDto.RecommendedAssigneeId,
                ReporterId = currentUserId.Value,
                Status = "Todo"
            };

            await _taskRepo.AddAsync(task, ct);
            createdTaskIds.Add(task.Id);
        }

        await _unitOfWork.SaveChangesAsync(ct);

        // Lưu Snapshot để hỗ trợ 1-Click Rollback trong 24h
        _snapshots[dto.SnapshotId] = (sprint.Id, createdTaskIds, DateTimeOffset.UtcNow);

        await _auditLogService.LogAsync("ApproveErumiRoadmap", nameof(Sprint), sprint.Id.ToString(), new { dto.SnapshotId, TaskCount = createdTaskIds.Count }, ct);

        return Result.Success();
    }

    public async Task<Result> RollbackRoadmapSnapshotAsync(RollbackErumiRoadmapSnapshotDto dto, CancellationToken ct = default)
    {
        if (!_snapshots.TryGetValue(dto.SnapshotId, out var snapshot))
        {
            return Result.Failure("Không tìm thấy snapshot hoặc thời gian rollback đã hết hạn.", 404);
        }

        // Xóa tasks đã sinh
        foreach (var taskId in snapshot.TaskIds)
        {
            var task = await _taskRepo.GetByIdAsync(taskId, ct);
            if (task != null)
            {
                await _taskRepo.DeleteAsync(task, ct);
            }
        }

        // Xóa sprint
        var sprint = await _sprintRepo.GetByIdAsync(snapshot.SprintId, ct);
        if (sprint != null)
        {
            await _sprintRepo.DeleteAsync(sprint, ct);
        }

        await _unitOfWork.SaveChangesAsync(ct);
        _snapshots.Remove(dto.SnapshotId);

        await _auditLogService.LogAsync("RollbackErumiRoadmap", nameof(Sprint), snapshot.SprintId.ToString(), new { dto.SnapshotId }, ct);

        return Result.Success();
    }
}
